# Generated by Django 6.0.4 on 2026-05-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(help_text='जैसे: ashtakvarga, dasha, ai_report', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='जैसे: अष्टकवर्ग बल', max_length=100)),
                ('is_paid', models.BooleanField(default=False, help_text='Tick करें अगर इसे सिर्फ Premium को दिखाना है')),
            ],
        ),
    ]
