# Generated by Django 6.0.4 on 2026-05-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_featurecontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chart_paid', models.BooleanField(default=False, verbose_name='चार्ट्स टैब (Paid)')),
                ('is_planets_paid', models.BooleanField(default=False, verbose_name='ग्रह स्थिति टैब (Paid)')),
                ('is_dasha_paid', models.BooleanField(default=False, verbose_name='दशा चक्र टैब (Paid)')),
                ('is_ai_paid', models.BooleanField(default=False, verbose_name='AI फलित टैब (Paid)')),
            ],
        ),
        migrations.DeleteModel(
            name='FeatureControl',
        ),
    ]
