# Generated by Django 6.0.4 on 2026-05-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tabsettings_delete_featurecontrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.AddField(
            model_name='lead',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, default='वेबसाइट', max_length=100, null=True),
        ),
    ]
