# Generated by Django 6.0.5 on 2026-05-19 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lead_phone_lead_mobile_alter_lead_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tabsettings',
            name='is_dosha_paid',
            field=models.BooleanField(default=False, verbose_name='दोष एवं उपाय टैब (Paid)'),
        ),
        migrations.AddField(
            model_name='tabsettings',
            name='is_pdf_paid',
            field=models.BooleanField(default=False, verbose_name='PDF डाउनलोड (Paid)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kundali_credits',
            field=models.IntegerField(default=0, verbose_name='Kundali Credits'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='milan_credits',
            field=models.IntegerField(default=0, verbose_name='Milan Credits'),
        ),
        migrations.AlterField(
            model_name='savedkundali',
            name='gender',
            field=models.CharField(default='पुरुष', max_length=10),
        ),
        migrations.AlterField(
            model_name='savedkundali',
            name='second',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savedkundali',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AIQuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kundali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_histories', to='core.savedkundali')),
            ],
        ),
        migrations.CreateModel(
            name='KundaliMilanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy_name', models.CharField(max_length=100)),
                ('girl_name', models.CharField(max_length=100)),
                ('total_score', models.FloatField()),
                ('manglik_status', models.CharField(blank=True, max_length=200, null=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('KUNDALI_51', 'Kundali Pack (3 Credits) - ₹51'), ('MILAN_51', 'Milan Pack (3 Credits) - ₹51'), ('COMBO_101', 'Combo Pack (5+5 Credits) - ₹101')], default='KUNDALI_51', max_length=20)),
                ('payment_reference', models.CharField(help_text='UPI Mobile Number OR 12-digit UTR', max_length=50)),
                ('amount', models.IntegerField(default=51)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
