# Generated by Django 6.0.5 on 2026-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tabsettings_is_dosha_paid_tabsettings_is_pdf_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundalimilanhistory',
            name='boy_nakshatra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kundalimilanhistory',
            name='boy_rashi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kundalimilanhistory',
            name='girl_nakshatra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kundalimilanhistory',
            name='girl_rashi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
