# Generated by Django 6.0.5 on 2026-05-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_kundalimilanhistory_boy_nakshatra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='kundali_credits',
            field=models.IntegerField(default=1, verbose_name='Kundali Credits'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='milan_credits',
            field=models.IntegerField(default=1, verbose_name='Milan Credits'),
        ),
    ]
