# Generated by Django 6.0.5 on 2026-05-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_activity_level_userprofile_finance_focus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_challenge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
