# Generated by Django 6.0.5 on 2026-05-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_daily_horoscope_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
