# Generated by Django 6.0.5 on 2026-06-04 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRashifal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('rashi_id', models.CharField(max_length=20)),
                ('general', models.TextField(blank=True, null=True)),
                ('career', models.TextField(blank=True, null=True)),
                ('love', models.TextField(blank=True, null=True)),
                ('health', models.TextField(blank=True, null=True)),
                ('lucky', models.TextField(blank=True, null=True)),
                ('upay', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('date', 'rashi_id')},
            },
        ),
    ]
