# Generated by Django 6.0.5 on 2026-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dailyrashifal'),
    ]

    operations = [
        migrations.CreateModel(
            name='JyotishLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='लेसन का नाम')),
                ('description', models.TextField(verbose_name='संक्षिप्त विवरण')),
                ('content_type', models.CharField(choices=[('PDF', 'PDF बुक / नोट्स'), ('VIDEO', 'वीडियो ट्यूटोरियल')], default='PDF', max_length=10, verbose_name='कंटेंट का प्रकार')),
                ('cover_emoji', models.CharField(default='📕', max_length=10, verbose_name='आइकॉन (Emoji)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='jyotish_books/', verbose_name='PDF फाइल (अगर हो)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='वीडियो लिंक (YouTube आदि)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ऐप में दिखाएं?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
