# Generated by Django 6.0.5 on 2026-06-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_jyotishlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='कैटेगरी का नाम (जैसे: बेसिक ज्योतिष)')),
                ('category_type', models.CharField(choices=[('PLAYLIST', '🎥 वीडियो प्लेलिस्ट'), ('LIBRARY', '📚 ई-लाइब्रेरी (PDF टॉपिक)')], max_length=20, verbose_name='प्रकार')),
                ('order', models.IntegerField(default=0, verbose_name='क्रम (Order) - ऊपर दिखाने के लिए 1 लिखें')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='टाइटल')),
                ('description', models.TextField(verbose_name='विवरण')),
                ('cover_emoji', models.CharField(default='📕', max_length=10, verbose_name='आइकॉन (Emoji)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='jyotish_books/', verbose_name='PDF फाइल')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='वीडियो लिंक')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.learncategory', verbose_name='किस प्लेलिस्ट/लाइब्रेरी में डालें?')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='JyotishLesson',
        ),
    ]
