# Generated by Django 6.0.5 on 2026-06-05 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_learncategory_learnitem_delete_jyotishlesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='शीर्षक (Title)')),
                ('message', models.TextField(verbose_name='संदेश (Message)')),
                ('notification_type', models.CharField(choices=[('DAILY', 'दैनिक राशिफल'), ('GOCHAR', 'गोचर परिवर्तन'), ('DASHA', 'दशा परिवर्तन'), ('FESTIVAL', 'त्यौहार / विशेष उपाय'), ('SYSTEM', 'सिस्टम अलर्ट')], default='DAILY', max_length=20)),
                ('is_read', models.BooleanField(default=False, verbose_name='क्या पढ़ लिया गया?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
