# Generated by Django 6.0.5 on 2026-06-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_usernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_horoscope_text',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='horoscope_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_chat_id',
        ),
    ]
