# Generated by Django 6.0.5 on 2026-06-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_learnitem_pdf_url'),
        ('core', '0018_remove_userprofile_daily_horoscope_text_and_more'),
    ]

    operations = [
    ]
