# Generated by Django 6.0.5 on 2026-06-08 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20260606_1355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HastRekhaReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_type', models.CharField(choices=[('दाहिना हाथ', 'दाहिना हाथ (Right Hand)'), ('बायाँ हाथ', 'बायाँ हाथ (Left Hand)')], default='दाहिना हाथ', max_length=20)),
                ('prediction', models.TextField(verbose_name='हस्त रेखा विश्लेषण')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hast_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
