# Generated by Django 6.0.5 on 2026-10-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_aichatsession_aichatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Chal rahi hai'), ('SUCCESS', 'Sab theek'), ('PARTIAL', 'Kuch fail'), ('FAILED', 'Sab fail'), ('INTERRUPTED', 'Adhoori rahi')], default='RUNNING', max_length=12)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('users_ok', models.PositiveIntegerField(default=0)),
                ('users_failed', models.PositiveIntegerField(default=0)),
                ('users_no_kundali', models.PositiveIntegerField(default=0)),
                ('notifications_sent', models.PositiveIntegerField(default=0)),
                ('errors', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
