"""
Django settings for trikal_portal project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import dj_database_url
from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_(1@ran2op0v^mhq@2zun67n$3&*9+t8gfvv(ayi_5%(q4%*yi'

DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  # 🚀 यह हमने अभी जोड़ा है
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trikal_portal.urls'

TEMPLATES = [
{
'BACKEND': 'django.template.backends.django.DjangoTemplates',
'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trikal_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#database

import dj_database_url

# यहाँ नीचे वाले कोटेशन मार्क्स (" ") के अंदर अपना असली Render वाला URL पेस्ट करें
RENDER_DB_URL = "postgresql://trikal_user:pS1IvOdD0g1u225MPYBDXCtO3mblzAFk@dpg-d88sd20js32c73a08bb0-a.singapore-postgres.render.com/trikal"



# settings.py में पुराना DATABASES ब्लॉक ढूंढकर उसे इस प्रकार अपडेट करें:

import sys

# चेक करें कि क्या कोड मोबाइल (Pydroid) पर चल रहा है
IS_PYDROID = 'pydroid3' in sys.executable or 'ru.iiec.pydroid3' in sys.prefix

if IS_PYDROID:
    # मोबाइल के लिए लोकल SQLite डेटाबेस
import sys
import dj_database_url  # सुनिश्चित करें कि यह ऊपर import किया गया हो

# चेक करें कि क्या कोड मोबाइल (Pydroid) पर चल रहा है
IS_PYDROID = 'pydroid3' in sys.executable or 'ru.iiec.pydroid3' in sys.prefix

if IS_PYDROID:
    # 1. Pydroid के लिए लोकल SQLite डेटाबेस (जिससे आपका Pydroid क्रैश नहीं होगा)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # 2. Render (Live Server) के लिए आपका ओरिजिनल कोड
    DATABASES = {
        'default': dj_database_url.config(
            default=RENDER_DB_URL, # यह वेरिएबल आपकी फाइल में ऊपर कहीं डिफाइन होगा
            conn_max_age=0,
            conn_health_checks=True,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # यह लाइन बहुत जरूरी है


# 🚀 यह नई लाइन जोड़नी है ताकि जांगो को CSS मिल जाए
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Email Configuration for Live Alerts
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nileshdave1511@gmail.com'  # 👈 आपका असली Gmail
EMAIL_HOST_PASSWORD = 'wqqy hqwd vwnz thby'  # 👈 स्क्रीनशॉट वाला 16-अक्षरों का सीक्रेट कोड
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
